CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/baseline/checkpoint-200 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/baseline/checkpoint-200;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/baseline/checkpoint-400 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/baseline/checkpoint-400;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/baseline/checkpoint-600 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/baseline/checkpoint-600;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/baseline/checkpoint-800 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/baseline/checkpoint-800;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/baseline/checkpoint-1000 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/baseline/checkpoint-1000;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/baseline/checkpoint-1200 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/baseline/checkpoint-1200;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/baseline/checkpoint-1400 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/baseline/checkpoint-1400;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/baseline/checkpoint-1600 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/baseline/checkpoint-1600;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/baseline/checkpoint-1800 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/baseline/checkpoint-1800;


CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/bigvul/checkpoint-200 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/bigvul/checkpoint-200;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/bigvul/checkpoint-400 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/bigvul/checkpoint-400;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/bigvul/checkpoint-600 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/bigvul/checkpoint-600;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/bigvul/checkpoint-800 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/bigvul/checkpoint-800;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/bigvul/checkpoint-1000 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/bigvul/checkpoint-1000;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/bigvul/checkpoint-1200 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/bigvul/checkpoint-1200;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/bigvul/checkpoint-1400 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/bigvul/checkpoint-1400;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/bigvul/checkpoint-1600 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/bigvul/checkpoint-1600;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/bigvul/checkpoint-1800 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/bigvul/checkpoint-1800;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/bigvul/checkpoint-2000 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/bigvul/checkpoint-2000;


CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/juliet/checkpoint-200 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/juliet/checkpoint-200;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/juliet/checkpoint-400 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/juliet/checkpoint-400;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/juliet/checkpoint-600 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/juliet/checkpoint-600;
CUDA_VISIBLE_DEVICES=0 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/juliet/checkpoint-800 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/juliet/checkpoint-800;
CUDA_VISIBLE_DEVICES=0 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/juliet/checkpoint-1000 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/juliet/checkpoint-1000;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/juliet/checkpoint-1200 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/juliet/checkpoint-1200;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/juliet/checkpoint-1400 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/juliet/checkpoint-1400;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/juliet/checkpoint-1600 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/juliet/checkpoint-1600;
CUDA_VISIBLE_DEVICES=0 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/juliet/checkpoint-1800 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/juliet/checkpoint-1800;
CUDA_VISIBLE_DEVICES=0 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/juliet/checkpoint-2000 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/juliet/checkpoint-2000;


CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/vgx/checkpoint-200 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/vgx/checkpoint-200;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/vgx/checkpoint-400 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/vgx/checkpoint-400;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/vgx/checkpoint-600 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/vgx/checkpoint-600;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/vgx/checkpoint-800 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/vgx/checkpoint-800;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/vgx/checkpoint-1000 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/vgx/checkpoint-1000;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/vgx/checkpoint-1200 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/vgx/checkpoint-1200;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/vgx/checkpoint-1400 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/vgx/checkpoint-1400;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/vgx/checkpoint-1600 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/vgx/checkpoint-1600;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/vgx/checkpoint-1800 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/vgx/checkpoint-1800;
CUDA_VISIBLE_DEVICES=4 python evaluation.py --checkpoint-path /shd/zzr/CWE-Predict/output_models/vgx/checkpoint-2000 --eval-data-path /shd/zzr/CWE-Predict/dataset/test.json --output-data-path /shd/zzr/CWE-Predict/log/vgx/checkpoint-2000;
